### ISSUE TITLE
listen is not a function

### ISSUE THREAD

**Issue by AmanPatel18** [daniel-j/epsile#3]
var io = require('socket.io').listen(server);
                              ^

TypeError: require(...).listen is not a function
    at Object.<anonymous> (C:\Users\patel\Downloads\Compressed\epsile-master\epsile-server.js:13:31)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by Ho3pLi** [comment]
just remove .listen
